openapi: 3.0.3
info:
  title: AI Chat - Chat Management API
  description: Chat conversation management endpoints for AI chat application
  version: 1.0.0

paths:
  /api/chats:
    get:
      summary: List all conversations for current user
      security:
        - SessionCookie: []
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Conversation'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new conversation
      security:
        - SessionCookie: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 255
                  description: Optional title for the conversation (defaults to "New Chat")
      responses:
        '201':
          description: Conversation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/chats/{chat_id}:
    get:
      summary: Get a specific conversation
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: integer
      security:
        - SessionCookie: []
      responses:
        '200':
          description: Conversation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Access denied (not owned by user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a conversation
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: integer
      security:
        - SessionCookie: []
      responses:
        '204':
          description: Conversation deleted
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Access denied (not owned by user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Conversation:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        title:
          type: string
          example: "My First Chat"
        created_at:
          type: string
          format: date-time
          example: "2025-12-24T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-12-24T11:45:00Z"

    Error:
      type: object
      properties:
        detail:
          type: string
          example: "Conversation not found"

  securitySchemes:
    SessionCookie:
      type: apiKey
      in: cookie
      name: session_token
