openapi: 3.0.3
info:
  title: AI Chat - Message API
  description: Message handling endpoints for AI chat application
  version: 1.0.0

paths:
  /api/chats/{chat_id}/messages:
    get:
      summary: Get all messages for a conversation
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 200
          description: Maximum number of messages to return
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
          description: Number of messages to skip (for pagination)
      security:
        - SessionCookie: []
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Access denied (not owned by user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Send a message and get AI response
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: integer
      security:
        - SessionCookie: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  maxLength: 10000
                  description: Message content from user
      responses:
        '200':
          description: Message sent and AI response received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Invalid input (validation error)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Access denied (not owned by user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: AI service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: integer
          example: 1
        conversation_id:
          type: integer
          example: 1
        content:
          type: string
          example: "Hello, AI assistant!"
        sender:
          type: string
          enum: ['user', 'ai']
          example: "user"
        created_at:
          type: string
          format: date-time
          example: "2025-12-24T10:30:00Z"

    MessageResponse:
      type: object
      properties:
        user_message:
          $ref: '#/components/schemas/Message'
        ai_message:
          $ref: '#/components/schemas/Message'
        conversation_updated_at:
          type: string
          format: date-time
          example: "2025-12-24T10:30:05Z"

    Error:
      type: object
      properties:
        detail:
          type: string
          example: "AI service is currently unavailable. Please try again later."

  securitySchemes:
    SessionCookie:
      type: apiKey
      in: cookie
      name: session_token
