import uuid
from datetime import datetime
from typing import Optional

from fastapi_users import schemas
from pydantic import BaseModel

# These schemas DO NOT create tables. These are Pydantic schemas for the API layer. (Which presumably means that it makes it easier for us to understand/validate the input/outputs).


# What the API returns when you ask for a user
class UserRead(schemas.BaseUser[uuid.UUID]):
    pass  # Inherits: id, email, is_active, is_superuser, is_verified


# What you send when registering a new user
class UserCreate(schemas.BaseUserCreate):
    pass  # Inherits: email, password


# What you send when updating a user
class UserUpdate(schemas.BaseUserUpdate):
    pass  # Inherits: password, email, is_active, is_superuser, is_verified


# -- Conversations --
# We use BaseModel to ensure Pydantic enforces Data Validation. (The idea is that everything in pydantic seems to derieve from BaseModel).
class ConversationCreate(BaseModel):
    """
    Request model for creating a conversation.
    """

    # [We're not going to include the title field here because the title will be generated by the LLM from the first message.]
    pass


class ConversationResponse(BaseModel):
    """
    Response model for a conversation.
    """

    id: uuid.UUID
    user_id: uuid.UUID
    title: str
    created_at: datetime
    updated_at: datetime

    # TODO: Add these fields if you want to return full conversation metadata:
    # - agno_session_id: Optional[str] (for linking to Agno database)
    # - message_count: Optional[int] (total messages in conversation)
    # - last_message_at: Optional[datetime] (timestamp of last activity)
    # - is_archived: bool (if implementing archiving feature)
    # - tags: Optional[str] (if implementing tags)
    pass


class ChatRequest(BaseModel):
    """
    Request model for the chat endpoint.
    Args:
        question: The question to ask the Agno agent.
        conversation_id: The conversation ID to link messages to.
    """

    question: str
    conversation_id: Optional[uuid.UUID]


# API Response Models.
class ChatResponse(BaseModel):
    """
    This model is used to represent the response from the Agno agent.
    Args:
        response: The response from the Agno agent.
    Returns:
        A JSON object with a "response" key.
        The "response" key contains the response from the Agno agent.
    """

    # The response from the Agno agent.
    response: str
